import { apiClient, generateIdempotencyKey } from '@/shared/api/client'
import type { PagedResult } from '@/shared/types'
import type {
  CreateMovementRequest,
  MovementHistoryFilters,
  MovementResponse,
} from './types'

/**
 * Stock-movement API surface. All methods unwrap `response.data` at the boundary
 * so callers receive the typed payload directly. Errors are normalized by the
 * Axios interceptor to `ApiError` (rejected) — callers handle in try/catch.
 *
 * baseURL `/api` lives in the Axios singleton; paths here are written as
 * `/stock-movements` and resolve to `/api/stock-movements` via the Vite proxy.
 *
 * **FRONT-12**: `register` injects an `Idempotency-Key` header generated by
 * `generateIdempotencyKey()` (which wraps `crypto.randomUUID()` per the shared
 * client). One UUID per submit — the submit button is disabled while the
 * request is in flight to prevent double-click double-key.
 */
export const movementsApi = {
  /**
   * Register a new movement (Inbound or Outbound). Generates a fresh
   * Idempotency-Key per call. The submit button must be disabled while in flight
   * to guarantee one key per logical operation.
   */
  register: (req: CreateMovementRequest): Promise<MovementResponse> =>
    apiClient
      .post<MovementResponse>('/stock-movements', req, {
        headers: { 'Idempotency-Key': generateIdempotencyKey() },
      })
      .then((r) => r.data),

  /**
   * Paginated history with optional filters. Empty filter values are omitted
   * from the query string (Axios drops `undefined` params automatically).
   */
  list: (filters: MovementHistoryFilters = {}): Promise<PagedResult<MovementResponse>> =>
    apiClient
      .get<PagedResult<MovementResponse>>('/stock-movements', {
        params: {
          productId: filters.productId,
          startDate: filters.startDate,
          endDate: filters.endDate,
          page: filters.page ?? 1,
          pageSize: filters.pageSize ?? 30,
        },
      })
      .then((r) => r.data),

  /** Detail by id. */
  getById: (id: string): Promise<MovementResponse> =>
    apiClient.get<MovementResponse>(`/stock-movements/${id}`).then((r) => r.data),
}
